#
# Analyze repository with PSRule for Azure
#


# For PSRule for Azure documentation see:
# https://aka.ms/ps-rule-azure

# For action details see:
# https://aka.ms/ps-rule-action


name: Analyze Azure resources


# Run for main or PRs against main
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:


    - name: Checkout
      uses: actions/checkout@v2.3.5


    - name: Run PSRule analysis
      uses: Microsoft/ps-rule@v1.9.0
      with:
        modules: 'PSRule.Rules.Azure'